### ISSUE TITLE
question: nginx does not load balance

### ISSUE THREAD

**Issue by artemave** [lordelph/confd-demo#1]
Hello,

I read your post and it was really helpful. But the comments there seem to be closed and I need to ask a question. So I am opening the issue instead.

I cloned this repo and tried to run it in Vagrant cluster locally. All went well:

![](http://cl.ly/image/1R2m410x3m13/Image%202015-03-12%20at%2012.22.17%20pm.png)

But when I try to request through nginx, I get nginx default page instead of expected "hello world" from one of the apache servers:

![](http://cl.ly/image/0m041Z333T3F/Image%202015-03-12%20at%2012.24.36%20pm.png)

\* ignore `Failed Units` - that is from my previous experiments.

I have a feeling I am missing something stupidly obvious but I can't see what.

Thanks for your time!

**Comment by lordelph** [comment]
Sorry, I'd accidentally left comments disabled while dealing with a spam problem.

To diagnose your issue, I'd try two things
- first, check the generated nginx.conf - did confd manage to write a configuration with your apache containers referenced in it?
- if that checks out, try to figure out why the HUP signalling might have failed, maybe try `docker kill -s HUP nginx.service` or similar

**Comment by artemave** [comment]
I think I found the culprit. I was cross referencing your post with [this one](https://www.digitalocean.com/community/tutorials/how-to-use-confd-and-etcd-to-dynamically-reconfigure-services-in-coreos) and noticed that they `rm /etc/nginx/sites-enabled/default` in their `nginx.tmpl`. So I did the same and it fixed the issue.

**EDIT**

Correction: I didn't `rm /etc/nginx/sites-enabled/default`, but removed `include /etc/nginx/conf.d/*.conf;` from `nginx.tmpl`

**Comment by artemave** [comment]
On a separate note, the docker image you're pulling in [here](https://github.com/lordelph/confd-demo/blob/master/apache.service#L10) seems to be a private one. I couldn't access it so I changed it to `tutum/hello-world` (which seems to be used anyway) and that worked for me.

**Comment by artemave** [comment]
And since this ticket became a dumping ground for little issues with the post, here is another possible one: 

[reload_nginx.sh](https://github.com/lordelph/confd-demo/blob/master/confd-demo/etc/confd/reload_nginx.sh) references wrong docker container - `connect-lb-nginx`. I beleive it should be `nginx.service` instead.

**Comment by lordelph** [comment]
well spotted! I adapted the sample code from something I was working on but looks like I didn't catch all the references!
